package com.example.timeboxvibe.engine

/**
 * Localization strings ported from i18n.js.
 * Supports English, Chinese (Shinonome JIS X 0208-compatible), and Japanese.
 */
data class AppStrings(
    val title: String,
    val focusMode: String,
    val breakMode: String,
    val timer: String,
    val templates: String,
    val entropy: String,
    val start: String,
    val pause: String,
    val reset: String,
    val skip: String,
    val ticks: String,
    val vibe: String,
    val on: String,
    val off: String,
    val presetsTitle: String,
    val addCustom: String,
    val cancel: String,
    val focusThemePlaceholder: String,
    val focusingLabel: String,
    val unwindingLabel: String,
    val blockLimitLabel: String,
    val sessionLimitLabel: String,
    val enterTaskPrompt: String,
    val sessionLimit: String,
    val step: String,
    val of: String,
    val block: String,
    val entropyBomb: String,
    val entropyDesc: String,
    val addTaskPlaceholder: String,
    val addButton: String,
    val explodeButton: String,
    val detonatingButton: String,
    val missionLabel: String,
    val launchEmergency: String,
    val alarmSoundLabel: String,
    val volumeLabel: String,
    val showSettings: String,
    val hideSettings: String,
    val themeLabel: String,
    val localeTab: String,
    val audioTab: String,
    val systemTab: String,
    val languageLabel: String,
    val languageEnglish: String,
    val languageChinese: String,
    val languageJapanese: String,
    val focusToneLabel: String,
    val relaxToneLabel: String,
    val testFocusLabel: String,
    val testRelaxLabel: String,
    val strictLabel: String,
    val precisionLabel: String,
    val secureLabel: String,
    val authorizeLabel: String,
    val themeReimu: String,
    val themeMarisa: String,
    val themeAlice: String,
    val themeKaguya: String,
    val defaultTasks: List<String>,
    
    // Custom presets strings
    val presetNameLabel: String,
    val presetNamePlaceholder: String,
    val engineStyleLabel: String,
    val durationLabel: String,
    val minutes: String,
    val seconds: String,
    val bigBoxLabel: String,
    val smallLoopLabel: String,
    val sequenceLabel: String,
    val sequencePlaceholder: String,
    val unitLabel: String,
    val saveTemplate: String,
    val completionBehaviorLabel: String,
    val requireDismissalLabel: String,
    val autoProgressLabel: String,
    val classicBehaviorDesc: String,
    val dualBehaviorDesc: String,
    val dual5BehaviorDesc: String,
    val sequenceBehaviorDesc: String,
    val dualSequenceBehaviorDesc: String,
    val forgeTitle: String,
    val pageBasicsLabel: String,
    val pageParamsLabel: String,
    val focusLabel: String,
    val breakLabel: String,
    val macroBlockLabel: String,
    val mediumLoopLabel: String,
    val microLoopLabel: String,
    val calendarBlockLabel: String,
    val calendarTypeLabel: String,
    val calendarFocusValue: String,
    val calendarRelaxValue: String,
    val calendarBlockNameLabel: String,
    val calendarFocusThemePlaceholder: String,
    val calendarRelaxThemePlaceholder: String,
    val addBlockLabel: String,
    val deleteBlockLabel: String,
    val calendarBehaviorDesc: String,

    // Visuals settings
    val visualsHeader: String,
    val demosceneLabel: String,
    val nebulaLabel: String
)

fun getStrings(lang: String): AppStrings = when (lang) {
    "zh" -> AppStrings(
        title = "時光律動",
        focusMode = "専注模式",
        breakMode = "放松洗脳",
        timer = "計時器",
        templates = "時間模板",
        entropy = "任務炸弾",
        start = "開始",
        pause = "暫停",
        reset = "重置",
        skip = "跳過",
        ticks = "滴答",
        vibe = "振動",
        on = "開",
        off = "關",
        presetsTitle = "時間箱模板",
        addCustom = "自定義",
        cancel = "取消",
        focusThemePlaceholder = "現在要専注做什麼？",
        focusingLabel = "専注中",
        unwindingLabel = "放松中",
        blockLimitLabel = "区塊限制",
        sessionLimitLabel = "会話限制",
        enterTaskPrompt = "＞　輸入任務　＿",
        sessionLimit = "総倒計時",
        step = "当前第",
        of = "歩　／　共",
        block = "歩",
        entropyBomb = "无序任務炸弾",
        entropyDesc = "被各種繁瑣事情困住了？在下面輸入未完小任務，点撃【引爆】，讓随机律動協助踏出第一歩！",
        addTaskPlaceholder = "輸入一件超簡単、極低門檻的小事．．．",
        addButton = "添加",
        explodeButton = "引爆　／　随机挑選",
        detonatingButton = "正在引爆．．．",
        missionLabel = "恭喜！專屬任務已鎖定：",
        launchEmergency = "開啓　９０秒冲刺并立刻執行！",
        alarmSoundLabel = "鬧鐘鈴声",
        volumeLabel = "鈴声音量",
        showSettings = "系統設置",
        hideSettings = "關閉設置",
        themeLabel = "界面配色主題",
        localeTab = "語言",
        audioTab = "音頻",
        systemTab = "系統",
        languageLabel = "語言",
        languageEnglish = "英語",
        languageChinese = "中文",
        languageJapanese = "日語",
        focusToneLabel = "専注提示音",
        relaxToneLabel = "休息提示音",
        testFocusLabel = "測試専注音",
        testRelaxLabel = "測試休息音",
        strictLabel = "厳格模式",
        precisionLabel = "精確鬧鐘",
        secureLabel = "已授権",
        authorizeLabel = "授権",
        themeReimu = "霊梦紅",
        themeMarisa = "魔理沙琥珀",
        themeAlice = "愛麗絲藍",
        themeKaguya = "輝夜紫",
        defaultTasks = listOf("整理工作臺", "写出一句論文或工作文案", "去洗　３　个碗", "回復或帰档　１　封郵件", "站起来拉伸或走動　６０秒"),
        
        presetNameLabel = "模板名称",
        presetNamePlaceholder = "例如：我的復習螺旋",
        engineStyleLabel = "計時器机制",
        durationLabel = "持続時長",
        minutes = "分鐘",
        seconds = "秒",
        bigBoxLabel = "大時間箱　（総時長）",
        smallLoopLabel = "小動作循環",
        sequenceLabel = "時間序列　（用英文逗号分隔数字）",
        sequencePlaceholder = "例如：１０，　８，　６，　４，　２",
        unitLabel = "数字単位",
        saveTemplate = "保存模板",
        completionBehaviorLabel = "完成行為",
        requireDismissalLabel = "需要手動消除　（鬧鐘）",
        autoProgressLabel = "自動進行下階段",
        classicBehaviorDesc = "應用于単次倒計時。",
        dualBehaviorDesc = "應用于小動作循環。大時間箱（総時長）在結束時総是会響鈴。",
        dual5BehaviorDesc = "應用于中等循環。大時間箱（総時長）在結束時総是会響鈴，微観秒表自動循環。",
        sequenceBehaviorDesc = "應用于歩驟之間的過渡階段。最后一个歩驟結束時総是会響鈴。",
        dualSequenceBehaviorDesc = "應用于大塊之間的過渡階段。小動作循環自動循環，最后一个大塊結束時総是会響鈴。",
        forgeTitle = "数据録入　／　鍛造",
        pageBasicsLabel = "第　１　／　２　頁",
        pageParamsLabel = "第　２　／　２　頁",
        focusLabel = "専注",
        breakLabel = "休息",
        macroBlockLabel = "宏区塊",
        mediumLoopLabel = "中循環",
        microLoopLabel = "微循環",
        calendarBlockLabel = "区塊",
        calendarTypeLabel = "類型",
        calendarFocusValue = "専注",
        calendarRelaxValue = "放松",
        calendarBlockNameLabel = "区塊標籤",
        calendarFocusThemePlaceholder = "専注主題",
        calendarRelaxThemePlaceholder = "放松主題",
        addBlockLabel = "添加区塊",
        deleteBlockLabel = "削除区塊",
        calendarBehaviorDesc = "日程区塊始終需要手動確認。",

        // Visuals settings (Chinese)
        visualsHeader = "視覚",
        demosceneLabel = "演示場特效",
        nebulaLabel = "背景星云"
    )
    "ja" -> AppStrings(
        title = "タイムボックス",
        focusMode = "集中モード",
        breakMode = "リラックス中",
        timer = "タイマー",
        templates = "テンプレート",
        entropy = "ランダム選択",
        start = "スタート",
        pause = "一時停止",
        reset = "リセット",
        skip = "スキップ",
        ticks = "秒針音",
        vibe = "バイブ",
        on = "オン",
        off = "オフ",
        presetsTitle = "テンプレート",
        addCustom = "新規作成",
        cancel = "キャンセル",
        focusThemePlaceholder = "何に集中しますか？",
        focusingLabel = "集中中",
        unwindingLabel = "休憩中",
        blockLimitLabel = "ブロック上限",
        sessionLimitLabel = "セッション上限",
        enterTaskPrompt = "＞　タスク入力　＿",
        sessionLimit = "セッション全体",
        step = "ステップ",
        of = "　／　全",
        block = "段階",
        entropyBomb = "エントロピー爆弾",
        entropyDesc = "何をすべきか迷って動けなくなっていませんか？　タスクを書き出し、【爆破】ボタンを押してランダムに１つ選びましょう！",
        addTaskPlaceholder = "すぐ終わる簡単なタスクを入力．．．",
        addButton = "追加",
        explodeButton = "爆破する　／　１つ選ぶ",
        detonatingButton = "爆破中．．．",
        missionLabel = "あなたのミッションはこちらです：",
        launchEmergency = "９０秒タイマーを起動して開始！",
        alarmSoundLabel = "アラーム音設定",
        volumeLabel = "アラーム音量",
        showSettings = "アプリ設定",
        hideSettings = "設定を閉じる",
        themeLabel = "カラーテーマ",
        localeTab = "言語",
        audioTab = "音響",
        systemTab = "システム",
        languageLabel = "言語",
        languageEnglish = "英語",
        languageChinese = "中国語",
        languageJapanese = "日本語",
        focusToneLabel = "集中音",
        relaxToneLabel = "休憩音",
        testFocusLabel = "集中音テスト",
        testRelaxLabel = "休憩音テスト",
        strictLabel = "厳格モード",
        precisionLabel = "正確アラーム",
        secureLabel = "許可済み",
        authorizeLabel = "許可",
        themeReimu = "霊夢の赤",
        themeMarisa = "魔理沙の琥珀",
        themeAlice = "アリスの青",
        themeKaguya = "輝夜の紫",
        defaultTasks = listOf("机の上を片付ける", "文章を１行書く", "お皿を３枚洗う", "メールを１通整理する", "立ち上がって６０秒間ストレッチする"),
        
        presetNameLabel = "テンプレート名",
        presetNamePlaceholder = "例：　集中スパイラル",
        engineStyleLabel = "タイマーの種類",
        durationLabel = "時間設定",
        minutes = "分",
        seconds = "秒",
        bigBoxLabel = "大タイマー　（全体の制限時間）",
        smallLoopLabel = "小タイマー　（行動ループ秒数）",
        sequenceLabel = "スパイラル時間設定　（カンマ区切りの数字）",
        sequencePlaceholder = "例：　１０，　８，　６，　４，　２",
        unitLabel = "数値の単位",
        saveTemplate = "保存する",
        completionBehaviorLabel = "完了時の動作",
        requireDismissalLabel = "手動停止が必要　（アラーム）",
        autoProgressLabel = "自動移行",
        classicBehaviorDesc = "単一のカウントダウンに適用されます。",
        dualBehaviorDesc = "小タイマー（行動ループ）に適用されます。大タイマー（全体の制限時間）終了時は常にアラームが鳴ります。",
        dual5BehaviorDesc = "中間アラームループに適用されます。大タイマー終了時は常にアラームが鳴り、秒針ループは常に自動移行します。",
        sequenceBehaviorDesc = "途中の各ステップに適用されます。最後のステップ終了時は常にアラームが鳴ります。",
        dualSequenceBehaviorDesc = "途中の各大タイマーブロックに適用されます。行動ループは常に自動移行し、最後のブロック終了時は常にアラームが鳴ります。",
        forgeTitle = "データ入力　／　フォージ",
        pageBasicsLabel = "ページ　１　／　２",
        pageParamsLabel = "ページ　２　／　２",
        focusLabel = "集中",
        breakLabel = "休憩",
        macroBlockLabel = "マクロブロック",
        mediumLoopLabel = "中ループ",
        microLoopLabel = "小ループ",
        calendarBlockLabel = "ブロック",
        calendarTypeLabel = "種類",
        calendarFocusValue = "集中",
        calendarRelaxValue = "休憩",
        calendarBlockNameLabel = "ブロック名",
        calendarFocusThemePlaceholder = "集中テーマ",
        calendarRelaxThemePlaceholder = "休憩テーマ",
        addBlockLabel = "ブロック追加",
        deleteBlockLabel = "ブロック削除",
        calendarBehaviorDesc = "カレンダーブロックは常に手動確認が必要です。",

        // Visuals settings (Japanese)
        visualsHeader = "ビジュアル",
        demosceneLabel = "デモシーン演出",
        nebulaLabel = "背景星雲"
    )
    else -> AppStrings(
        title = "ＴｉｍｅＢｏｘ　Ｖｉｂｅ",
        focusMode = "Ｆｏｃｕｓ　Ｍｏｄｅ",
        breakMode = "Ｕｎｗｉｎｄｉｎｇ",
        timer = "Ｔｉｍｅｒ",
        templates = "Ｔｅｍｐｌａｔｅｓ",
        entropy = "Ｅｎｔｒｏｐｙ",
        start = "Ｓｔａｒｔ",
        pause = "Ｐａｕｓｅ",
        reset = "Ｒｅｓｅｔ",
        skip = "Ｓｋｉｐ",
        ticks = "Ｔｉｃｋｓ",
        vibe = "Ｖｉｂｅ",
        on = "Ｏｎ",
        off = "Ｏｆｆ",
        presetsTitle = "Ｔｅｍｐｌａｔｅｓ",
        addCustom = "Ｃｕｓｔｏｍ",
        cancel = "Ｃａｎｃｅｌ",
        focusThemePlaceholder = "Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｆｏｃｕｓｉｎｇ　ｏｎ？",
        focusingLabel = "ＦＯＣＵＳＩＮＧ",
        unwindingLabel = "ＵＮＷＩＮＤＩＮＧ",
        blockLimitLabel = "ＢＬＯＣＫ　ＬＩＭＩＴ",
        sessionLimitLabel = "ＳＥＳＳＩＯＮ　ＬＩＭＩＴ",
        enterTaskPrompt = "＞　ＥＮＴＥＲ　ＴＡＳＫ　＿",
        sessionLimit = "Ｓｅｓｓｉｏｎ　Ｌｉｍｉｔ",
        step = "Ｓｔｅｐ",
        of = "ｏｆ",
        block = "Ｂｌｏｃｋ",
        entropyBomb = "Ｅｎｔｒｏｐｙ　Ｂｏｍｂ",
        entropyDesc = "Ｓｔｕｃｋ　ｉｎ　ａｎａｌｙｓｉｓ　ｐａｒａｌｙｓｉｓ？　Ｅｎｔｅｒ　ｙｏｕｒ　ｔａｓｋｓ　ｂｅｌｏｗ，　ｃｌｉｃｋ　ＥＸＰＬＯＤＥ，　ａｎｄ　ｌｅｔ　ｅｎｔｒｏｐｙ　ｐｉｃｋ　ｗｈａｔ　ｔｏ　ｓｔａｒｔ　ｎｏｗ！",
        addTaskPlaceholder = "Ｅｎｔｅｒ　ａ　ｓｍａｌｌ，　ｌｏｗ‐ｅｆｆｏｒｔ　ｔａｓｋ．．．",
        addButton = "Ａｄｄ",
        explodeButton = "Ｅｘｐｌｏｄｅ　／　Ｐｉｃｋ　Ｒａｎｄｏｍ",
        detonatingButton = "Ｄｅｔｏｎａｔｉｎｇ．．．",
        missionLabel = "Ｙｏｕｒ　Ｍｉｓｓｉｏｎ，　Ｓｈｏｕｌｄ　Ｙｏｕ　Ｃｈｏｏｓｅ　Ｔｏ　Ａｃｃｅｐｔ：",
        launchEmergency = "Ｌａｕｎｃｈ　９０ｓ　Ｂｏｘ　＆　Ｄｏ　Ｉｔ！",
        alarmSoundLabel = "Ａｌａｒｍ　Ｓｏｕｎｄ",
        volumeLabel = "Ｖｏｌｕｍｅ",
        showSettings = "Ｓｅｔｔｉｎｇｓ",
        hideSettings = "Ｃｌｏｓｅ　Ｓｅｔｔｉｎｇｓ",
        themeLabel = "Ｉｎｔｅｒｆａｃｅ　Ｔｈｅｍｅ",
        localeTab = "Ｌｏｃａｌｅ",
        audioTab = "Ａｕｄｉｏ",
        systemTab = "Ｓｙｓｔｅｍ",
        languageLabel = "Ｌａｎｇｕａｇｅ",
        languageEnglish = "Ｅｎｇｌｉｓｈ",
        languageChinese = "Ｃｈｉｎｅｓｅ",
        languageJapanese = "Ｊａｐａｎｅｓｅ",
        focusToneLabel = "Ｆｏｃｕｓ　Ｔｏｎｅ",
        relaxToneLabel = "Ｒｅｌａｘ　Ｔｏｎｅ",
        testFocusLabel = "Ｔｅｓｔ　Ｆｏｃｕｓ",
        testRelaxLabel = "Ｔｅｓｔ　Ｒｅｌａｘ",
        strictLabel = "Ｓｔｒｉｃｔ",
        precisionLabel = "Ｐｒｅｃｉｓｉｏｎ",
        secureLabel = "Ｓｅｃｕｒｅ",
        authorizeLabel = "Ａｕｔｈｏｒｉｚｅ",
        themeReimu = "Ｒｅｉｍｕ　Ｒｅｄ",
        themeMarisa = "Ｍａｒｉｓａ　Ａｍｂｅｒ",
        themeAlice = "Ａｌｉｃｅ　Ｂｌｕｅ",
        themeKaguya = "Ｋａｇｕｙａ　Ｐｕｒｐｌｅ",
        defaultTasks = listOf("Ｔｉｄｙ　ｕｐ　ｗｏｒｋｓｐａｃｅ", "Ｗｒｉｔｅ　１　ｓｅｎｔｅｎｃｅ", "Ｗａｓｈ　３　ｄｉｓｈｅｓ", "Ｆｉｌｅ　１　ｅｍａｉｌ", "Ｓｔｒｅｔｃｈ　／　ｗａｌｋ　ｆｏｒ　６０ｓ"),
        
        presetNameLabel = "Ｐｒｅｓｅｔ　Ｎａｍｅ",
        presetNamePlaceholder = "ｅ．ｇ．　Ｍｙ　Ｓｔｕｄｙ　Ｓｐｉｒａｌ",
        engineStyleLabel = "Ｅｎｇｉｎｅ　Ｓｔｙｌｅ",
        durationLabel = "Ｄｕｒａｔｉｏｎ",
        minutes = "Ｍｉｎｕｔｅｓ",
        seconds = "Ｓｅｃｏｎｄｓ",
        bigBoxLabel = "Ｂｉｇ　Ｂｏｘ　（Ｏｖｅｒａｌｌ）",
        smallLoopLabel = "Ｓｍａｌｌ　Ａｃｔｉｏｎ　Ｌｏｏｐ",
        sequenceLabel = "Ｉｎｔｅｒｖａｌ　Ｓｅｑｕｅｎｃｅ　（ｃｏｍｍａ‐ｓｅｐａｒａｔｅｄ　ｎｕｍｂｅｒｓ）",
        sequencePlaceholder = "ｅ．ｇ．　１０，　８，　６，　４，　２",
        unitLabel = "Ｕｎｉｔ　ｏｆ　Ｎｕｍｂｅｒｓ",
        saveTemplate = "Ｓａｖｅ　Ｔｅｍｐｌａｔｅ",
        completionBehaviorLabel = "Ｃｏｍｐｌｅｔｉｏｎ　Ｂｅｈａｖｉｏｒ",
        requireDismissalLabel = "Ｒｅｑｕｉｒｅ　Ｄｉｓｍｉｓｓａｌ　（Ａｌａｒｍ）",
        autoProgressLabel = "Ａｕｔｏ‐Ｐｒｏｇｒｅｓｓ",
        classicBehaviorDesc = "Ａｐｐｌｉｅｓ　ｔｏ　ｔｈｅ　ｓｉｎｇｕｌａｒ　ｃｏｕｎｔｄｏｗｎ．",
        dualBehaviorDesc = "Ａｐｐｌｉｅｓ　ｔｏ　ｔｈｅ　Ｓｍａｌｌ　Ａｃｔｉｏｎ　Ｌｏｏｐ．　Ｔｈｅ　Ｂｉｇ　Ｂｏｘ　（Ｏｖｅｒａｌｌ）　ａｌｗａｙｓ　ａｌａｒｍｓ　ａｔ　ｔｈｅ　ｅｎｄ．",
        dual5BehaviorDesc = "Ａｐｐｌｉｅｓ　ｔｏ　ｔｈｅ　Ｍｅｄｉｕｍ　Ａｌａｒｍ　Ｌｏｏｐ．　Ｔｈｅ　Ｍａｃｒｏ　Ｂｌｏｃｋ　（Ｂｉｇ）　ａｌｗａｙｓ　ａｌａｒｍｓ　ａｔ　ｔｈｅ　ｅｎｄ．　Ｍｉｃｒｏ　ｓｔｏｐｗａｔｃｈ　ｌｏｏｐ　ａｌｗａｙｓ　ａｕｔｏ‐ｐｒｏｇｒｅｓｓｅｓ．",
        sequenceBehaviorDesc = "Ａｐｐｌｉｅｓ　ｔｏ　ｉｎｔｅｒｍｅｄｉａｔｅ　ｓｔｅｐｓ．　Ｔｈｅ　ｆｉｎａｌ　ｓｔｅｐ　ａｌｗａｙｓ　ａｌａｒｍｓ　ａｔ　ｔｈｅ　ｅｎｄ．",
        dualSequenceBehaviorDesc = "Ａｐｐｌｉｅｓ　ｔｏ　ｉｎｔｅｒｍｅｄｉａｔｅ　ｂｉｇ　ｂｌｏｃｋｓ．　Ｓｍａｌｌ　ａｃｔｉｏｎ　ｌｏｏｐ　ａｌｗａｙｓ　ａｕｔｏ‐ｐｒｏｇｒｅｓｓｅｓ，　ａｎｄ　ｔｈｅ　ｆｉｎａｌ　ｂｌｏｃｋ　ａｌｗａｙｓ　ａｌａｒｍｓ　ａｔ　ｔｈｅ　ｅｎｄ．",
        forgeTitle = "ＤＡＴＡ　ＥＮＴＲＹ　／　ＦＯＲＧＥ",
        pageBasicsLabel = "ＰＡＧＥ　１　／　２",
        pageParamsLabel = "ＰＡＧＥ　２　／　２",
        focusLabel = "Ｆｏｃｕｓ",
        breakLabel = "Ｂｒｅａｋ",
        macroBlockLabel = "ＭＡＣＲＯ　ＢＬＯＣＫ",
        mediumLoopLabel = "ＭＥＤＩＵＭ　ＬＯＯＰ",
        microLoopLabel = "ＭＩＣＲＯ　ＬＯＯＰ",
        calendarBlockLabel = "ＢＬＯＣＫ",
        calendarTypeLabel = "ＴＹＰＥ",
        calendarFocusValue = "ＦＯＣＵＳ",
        calendarRelaxValue = "ＲＥＬＡＸ",
        calendarBlockNameLabel = "ＢＬＯＣＫ　ＬＡＢＥＬ",
        calendarFocusThemePlaceholder = "ＦＯＣＵＳ　ＴＨＥＭＥ",
        calendarRelaxThemePlaceholder = "ＲＥＬＡＸ　ＴＨＥＭＥ",
        addBlockLabel = "ＡＤＤ　ＢＬＯＣＫ",
        deleteBlockLabel = "ＤＥＬ　ＢＬＯＣＫ",
        calendarBehaviorDesc = "Ｃａｌｅｎｄａｒ　ｂｌｏｃｋｓ　ａｌｗａｙｓ　ｒｅｑｕｉｒｅ　ｄｉｓｍｉｓｓａｌ．",

        // Visuals settings (English)
        visualsHeader = "ＶＩＳＵＡＬＳ",
        demosceneLabel = "Ｄｅｍｏｓｃｅｎｅ　Ｅｆｆｅｃｔｓ",
        nebulaLabel = "Ｂａｃｋｇｒｏｕｎｄ　Ｎｅｂｕｌａ"
    )
}
