#!/usr/bin/env python3
"""
de_casteljau_oracle.py

Subdivide quadratic/cubic Bezier curves and report snapped segment quality.

Usage:
  python tools/math_oracles/de_casteljau_oracle.py --points "0,0 32,64 64,0" --tolerance 0.5
  python tools/math_oracles/de_casteljau_oracle.py --points "0,0 32,64 64,64 96,0" --kotlin
"""

from __future__ import annotations

import argparse
import math
import json


def parse_points(s):
    pts = []
    for part in s.split():
        x, y = part.split(",")
        pts.append((float(x), float(y)))
    if len(pts) not in (3,4):
        raise ValueError("provide 3 quadratic or 4 cubic points")
    return pts


def lerp(a, b, t):
    return (a[0] + (b[0]-a[0])*t, a[1] + (b[1]-a[1])*t)


def point(pts, t):
    cur = pts[:]
    while len(cur) > 1:
        cur = [lerp(cur[i], cur[i+1], t) for i in range(len(cur)-1)]
    return cur[0]


def flatness(pts):
    # max distance of inner controls to chord
    a, b = pts[0], pts[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]
    denom = math.hypot(dx, dy) or 1.0
    maxd = 0.0
    for p in pts[1:-1]:
        d = abs(dy*p[0] - dx*p[1] + b[0]*a[1] - b[1]*a[0]) / denom
        maxd = max(maxd, d)
    return maxd


def subdivide(pts):
    left = [pts[0]]
    right = [pts[-1]]
    cur = pts[:]
    while len(cur) > 1:
        nxt = [lerp(cur[i], cur[i+1], 0.5) for i in range(len(cur)-1)]
        left.append(nxt[0])
        right.append(nxt[-1])
        cur = nxt
    return left, list(reversed(right))


def recursive(pts, tolerance, out, depth=0, max_depth=16):
    if depth >= max_depth or flatness(pts) <= tolerance:
        out.append(pts[-1])
        return
    l, r = subdivide(pts)
    recursive(l, tolerance, out, depth+1, max_depth)
    recursive(r, tolerance, out, depth+1, max_depth)


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--points", required=True)
    p.add_argument("--tolerance", type=float, default=0.5)
    p.add_argument("--kotlin", action="store_true")
    args = p.parse_args(argv)

    pts = parse_points(args.points)
    out = [pts[0]]
    recursive(pts, args.tolerance, out)
    snapped = [(round(x), round(y)) for x, y in out]
    dedup = []
    for pnt in snapped:
        if not dedup or dedup[-1] != pnt:
            dedup.append(pnt)

    report = {
        "input": pts,
        "tolerance": args.tolerance,
        "segments": max(0, len(dedup)-1),
        "points": dedup,
        "duplicatesRemoved": len(snapped)-len(dedup),
    }
    if args.kotlin:
        print("// GENERATED BY de_casteljau_oracle.py. DO NOT EDIT BY HAND.")
        print("intArrayOf(")
        for x, y in dedup:
            print(f"    {x}, {y},")
        print(")")
    else:
        print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
