#!/usr/bin/env python3
"""
gen_lut.py

Generate deterministic Kotlin lookup tables for sine/cosine/waveforms.

Usage:
  python tools/math_oracles/gen_lut.py --kind sin --size 1024 --q 15 --object GeneratedSinLut
  python tools/math_oracles/gen_lut.py --kind cos --size 1024 --q 15 --package engine.generated --out GeneratedCosLut.kt
  python tools/math_oracles/gen_lut.py --kind triangle --size 256 --q 15
"""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path


def wave(kind: str, t: float) -> float:
    # t in [0, 1)
    if kind == "sin":
        return math.sin(2.0 * math.pi * t)
    if kind == "cos":
        return math.cos(2.0 * math.pi * t)
    if kind == "saw":
        return 2.0 * t - 1.0
    if kind == "square":
        return 1.0 if t < 0.5 else -1.0
    if kind == "triangle":
        # -1..1..-1
        return 4.0 * abs(t - 0.5) - 1.0
    raise ValueError(f"unknown kind: {kind}")


def emit_kotlin(values, object_name, const_name, package=None, command=None):
    h = hashlib.sha256(",".join(map(str, values)).encode()).hexdigest()[:16]
    lines = []
    if package:
        lines.append(f"package {package}")
        lines.append("")
    lines.append("// GENERATED BY gen_lut.py. DO NOT EDIT BY HAND.")
    if command:
        lines.append(f"// Command: {command}")
    lines.append(f"// SHA256-16: {h}")
    lines.append(f"internal object {object_name} {{")
    lines.append(f"    const val SIZE: Int = {len(values)}")
    lines.append(f"    val {const_name}: IntArray = intArrayOf(")
    for i in range(0, len(values), 12):
        chunk = ", ".join(str(v) for v in values[i:i+12])
        lines.append(f"        {chunk},")
    lines.append("    )")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--kind", choices=["sin", "cos", "saw", "square", "triangle"], required=True)
    p.add_argument("--size", type=int, default=1024)
    p.add_argument("--q", type=int, default=15, help="Fixed-point fractional bits. q=15 means scale 32767.")
    p.add_argument("--object", default="GeneratedLut")
    p.add_argument("--const", default="DATA")
    p.add_argument("--package", default=None)
    p.add_argument("--out", type=Path)
    args = p.parse_args(argv)

    if args.size <= 0 or args.size & (args.size - 1) != 0:
        raise SystemExit("size must be a positive power of two")
    scale = (1 << args.q) - 1
    vals = []
    for i in range(args.size):
        v = wave(args.kind, i / args.size)
        vals.append(int(round(max(-1.0, min(1.0, v)) * scale)))

    src = emit_kotlin(vals, args.object, args.const, args.package, command=" ".join(sys_argv_safe()))
    if args.out:
        args.out.write_text(src, encoding="utf-8")
        print(f"Wrote {args.out} entries={len(vals)} q={args.q}")
    else:
        print(src)


def sys_argv_safe():
    import sys
    return [a.replace("\n", " ") for a in sys.argv]


if __name__ == "__main__":
    main()
