#!/usr/bin/env python3
"""
kotlin_const_emit.py

Emit Kotlin IntArray/FloatArray constants from JSON arrays.

Usage:
  python tools/math_oracles/kotlin_const_emit.py values.json --type Int --object MyConstants --name DATA
"""

from __future__ import annotations

import argparse, json, hashlib
from pathlib import Path


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("input", type=Path)
    p.add_argument("--type", choices=["Int","Float","Short","Byte"], default="Int")
    p.add_argument("--object", default="GeneratedConstants")
    p.add_argument("--name", default="DATA")
    p.add_argument("--package")
    p.add_argument("--out", type=Path)
    args = p.parse_args(argv)

    vals = json.loads(args.input.read_text(encoding="utf-8"))
    if not isinstance(vals, list):
        raise SystemExit("input must be a JSON list")
    arr_type = {"Int":"IntArray", "Float":"FloatArray", "Short":"ShortArray", "Byte":"ByteArray"}[args.type]
    ctor = {"Int":"intArrayOf", "Float":"floatArrayOf", "Short":"shortArrayOf", "Byte":"byteArrayOf"}[args.type]
    h = hashlib.sha256(json.dumps(vals, separators=(",",":")).encode()).hexdigest()[:16]

    lines = []
    if args.package:
        lines += [f"package {args.package}", ""]
    lines += [
        "// GENERATED BY kotlin_const_emit.py. DO NOT EDIT BY HAND.",
        f"// SHA256-16: {h}",
        f"internal object {args.object} {{",
        f"    val {args.name}: {arr_type} = {ctor}("
    ]
    for i in range(0, len(vals), 12):
        chunk = ", ".join(str(v) + ("f" if args.type == "Float" and isinstance(v, (int,float)) else "") for v in vals[i:i+12])
        lines.append(f"        {chunk},")
    lines += ["    )", "}"]
    src = "\n".join(lines) + "\n"
    if args.out:
        args.out.write_text(src, encoding="utf-8")
        print(f"Wrote {args.out}")
    else:
        print(src)


if __name__ == "__main__":
    main()
