#!/usr/bin/env python3
"""
repo_brief.py

Generate compact ENGINE_BRIEF.generated.md for Codex context compression.

Usage:
  python tools/math_oracles/repo_brief.py . --out ENGINE_BRIEF.generated.md
"""

from __future__ import annotations

import argparse
from pathlib import Path


SKIP = {".git",".gradle",".idea","build",".kotlin",".konan","node_modules","out"}
HOT_NAMES = ("update(", "render(", "onDraw(", "renderAudioBlock(")


def skip(p):
    return any(part in SKIP for part in p.parts)


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("root", nargs="?", default=".", type=Path)
    p.add_argument("--out", type=Path)
    args = p.parse_args(argv)
    root = args.root.resolve()

    kt = [x for x in root.rglob("*.kt") if x.is_file() and not skip(x)]
    hot = []
    interop = []
    palette = []
    render = []
    platform = []
    for f in kt:
        rel = f.relative_to(root)
        text = f.read_text(encoding="utf-8", errors="replace")
        s = str(rel).replace("\\","/")
        if any(h in text for h in HOT_NAMES):
            hot.append(s)
        if "kotlinx.cinterop" in text or "CPointer" in text or "StableRef" in text:
            interop.append(s)
        if "Palette" in text or "PaletteIndices" in text:
            palette.append(s)
        if "render" in s.lower() or "draw" in s.lower() or "renderer" in s.lower():
            render.append(s)
        if any(x in s for x in ("androidMain","iosMain","mingwX64Main")):
            platform.append(s)

    def section(name, items, limit=30):
        lines = [f"## {name}"]
        if not items:
            lines.append("- none found")
        else:
            for item in sorted(set(items))[:limit]:
                lines.append(f"- {item}")
            if len(set(items)) > limit:
                lines.append(f"- ... {len(set(items))-limit} more")
        return "\n".join(lines)

    out = "\n\n".join([
        "# ENGINE_BRIEF.generated.md",
        "Generated by repo_brief.py. Do not treat this as law; it is a map.",
        section("Hot Path Candidate Files", hot),
        section("C Interop Files", interop),
        section("Palette Files", palette),
        section("Renderer/Draw Files", render),
        section("Platform Files", platform),
        "## Suggested Audit Commands\n- python tools/law_check.py .\n- python tools/hotpath_audit.py .\n- python tools/cinterop_audit.py .",
    ]) + "\n"
    if args.out:
        args.out.write_text(out, encoding="utf-8")
        print(f"Wrote {args.out}")
    else:
        print(out)


if __name__ == "__main__":
    main()
